spring:
  data:
    rest:
      max-page-size: 3
      
server:
  port: 8090

security:
  basic:
    enabled: false
  user:
    password: password
    
logging:
  level:
    org.springframework.security: DEBUG
    
management:
  context-path: /manage
  port: 8099 